name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        uses: tweag/run-nix-shell@v0
        with:
          run: |
            task test

      - name: Build
        uses: tweag/run-nix-shell@v0
        with:
          run: |
            task build
